@startuml standard_class_delattr

start

:Name - string, name of an attribute<

:check the class' own dictionary;

if (found key?) then (Yes)
    :delete the key : value entry from the dictionary;
    
    stop
else (No)
    :raise AttributeError exception;
    
    stop
endif

@enduml